// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkswPC4IRNDfPra_IfgmInzZ4zay4pYt0',
    appId: '1:804814685089:web:6afd7adbd28d62cc9641e0',
    messagingSenderId: '804814685089',
    projectId: 'food-delivery-app-mh',
    authDomain: 'food-delivery-app-mh.firebaseapp.com',
    storageBucket: 'food-delivery-app-mh.firebasestorage.app',
    measurementId: 'G-M3VSX1Q2TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuel6pixCIydWb10eezZFHA6a5-LMbP4',
    appId: '1:804814685089:android:d88d2d4eae3ec34a9641e0',
    messagingSenderId: '804814685089',
    projectId: 'food-delivery-app-mh',
    storageBucket: 'food-delivery-app-mh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QUpjzbX5vI7iI-R6fmyOv3RIaeMv6jw',
    appId: '1:804814685089:ios:8469ee3f864d23b39641e0',
    messagingSenderId: '804814685089',
    projectId: 'food-delivery-app-mh',
    storageBucket: 'food-delivery-app-mh.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2QUpjzbX5vI7iI-R6fmyOv3RIaeMv6jw',
    appId: '1:804814685089:ios:8469ee3f864d23b39641e0',
    messagingSenderId: '804814685089',
    projectId: 'food-delivery-app-mh',
    storageBucket: 'food-delivery-app-mh.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkswPC4IRNDfPra_IfgmInzZ4zay4pYt0',
    appId: '1:804814685089:web:1e0ca8bc3586d8cc9641e0',
    messagingSenderId: '804814685089',
    projectId: 'food-delivery-app-mh',
    authDomain: 'food-delivery-app-mh.firebaseapp.com',
    storageBucket: 'food-delivery-app-mh.firebasestorage.app',
    measurementId: 'G-F64P3NJF32',
  );

}